parameters:
  root_password: linux
  admin_flavor: m1.large
  master_flavor: m1.large
  worker_flavor: m1.large
  worker_count: 2
  external_net: 
  # Make sure you use a CIDR that doesn't conflict with the CaaSP IPs:
  # https://github.com/kubic-project/salt/blob/master/pillar/params.sls#L51
  # https://github.com/kubic-project/velum/blob/master/app/controllers/setup_controller.rb#L34
  # If dns_nameserver is the same as CaaSPs dns_cluster_ip then the kube service
  # hostnames won't be resolved.
  internal_net_cidr: 192.168.0.0/24
  dns_nameserver: 
  # cpi parameters
  cpi_auth_url: 
  cpi_domain_name: 
  cpi_tenant_name: eu-de
  cpi_region: 
  cpi_username: 
  cpi_password: 
  cpi_monitor_max_retries: 4
  cpi_bs_version: auto
  cpi_ignore_volume_az: "true"
